version: '3.9'
services:

  php:
    image: ghcr.io/wod-serial/techno-wiki:0.0.43
    volumes:
      - home:/var/www/public_html:rw
      - images:/var/www/images:rw
      - php-config:/usr/local/etc/php-fpm.d:ro
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Europe/Moscow
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    networks:
      - tc-network

  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:6602:80"
    volumes:
      - nginx-config:/etc/nginx/conf.d:ro
      - home:/var/www/public_html:ro
    container_name: nginx
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Europe/Moscow
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
    networks:
      - tc-network


  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:6603:3306"
    environment:
      MYSQL_DATABASE: tc
      MYSQL_USER: tc
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql:rw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    networks:
      - tc-network


volumes:
  home:
  images:
  mysql:
  nginx-config:
  php-config:

networks:
  tc-network:
    driver: bridge
